### ISSUE TITLE
Docker Secondary HUB

### ISSUE THREAD

**Issue by fdabrao** [BryanKMorrow/uim#1]
Hello,

Do you think is that possible to run secondary Hub with Docker?

Regards,

Fernando

**Comment by bryankmorrow** [comment]
Yes, I've been playing around with this recently. I'll try and post my docker-compose file soon.

**Comment by fdabrao** [comment]
Hello Bryan,

Is yours tests played ok? I´m trying to use docker for using net_connect outside customer hub and change the origin, because today we have centralized hub for doing net_connect, but it has the same origin. It´s a pain to use it for permission.

Regards,

Fernando

**Comment by bryankmorrow** [comment]
Does your secondary hub need a tunnel, or just a static hub?

**Comment by fdabrao** [comment]
At this moment, it does not need tunnel.

**Comment by bryankmorrow** [comment]
Uploaded a secondary hub example:

https://github.com/BryanKMorrow/uim/commit/3c7866a54a51b10ce657fb08c77ecfd6b10d8713

**Comment by fdabrao** [comment]
Hello Bryan,

How did you work without tunnel? The hub probe never goes up. 
![image](https://user-images.githubusercontent.com/17049832/40469162-fab2d09c-5f05-11e8-86e8-6ced64625158.png)

I think to deploy probes we will have to use tunnel so. Any ideas for this situation?

Thanks
